CREATE TABLE "activities" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "kind" TEXT NOT NULL,
    "body" TEXT NOT NULL,
    "contact_id" BIGINT,
    "company_id" BIGINT,
    "deal_id" BIGINT,
    "created_at" BIGINT NOT NULL,
    "user_id" BIGINT,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_activities_by_kind" ON "activities" ("kind");
CREATE INDEX "index_activities_by_contact_id" ON "activities" ("contact_id");
CREATE INDEX "index_activities_by_company_id" ON "activities" ("company_id");
CREATE INDEX "index_activities_by_deal_id" ON "activities" ("deal_id");
CREATE INDEX "index_activities_by_user_id" ON "activities" ("user_id");
CREATE TABLE "login_attempts" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username_lower" TEXT NOT NULL,
    "failures" BIGINT NOT NULL,
    "locked_until" BIGINT,
    "last_failure_at" BIGINT NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_login_attempts_by_username_lower" ON "login_attempts" ("username_lower");
CREATE TABLE "users" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" TEXT NOT NULL,
    "username_lower" TEXT NOT NULL,
    "display_name" TEXT,
    "password_hash" TEXT,
    "role" TEXT NOT NULL,
    "totp_secret" TEXT,
    "active" BOOLEAN NOT NULL,
    "created_at" BIGINT NOT NULL,
    "last_login_at" BIGINT,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_users_by_username_lower" ON "users" ("username_lower");
CREATE TABLE "deals" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" TEXT NOT NULL,
    "value_cents" BIGINT NOT NULL,
    "stage" TEXT NOT NULL,
    "company_id" BIGINT,
    "contact_id" BIGINT,
    "expected_close" BIGINT,
    "notes" TEXT,
    "created_at" BIGINT NOT NULL,
    "created_by" BIGINT,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_deals_by_stage" ON "deals" ("stage");
CREATE INDEX "index_deals_by_company_id" ON "deals" ("company_id");
CREATE INDEX "index_deals_by_contact_id" ON "deals" ("contact_id");
CREATE INDEX "index_deals_by_created_by" ON "deals" ("created_by");
CREATE TABLE "sessions" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "token_hash" TEXT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "created_at" BIGINT NOT NULL,
    "expires_at" BIGINT NOT NULL,
    "revoked_at" BIGINT,
    "user_agent" TEXT,
    "ip" TEXT,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "index_sessions_by_token_hash" ON "sessions" ("token_hash");
CREATE INDEX "index_sessions_by_user_id" ON "sessions" ("user_id");
CREATE TABLE "companies" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT NOT NULL,
    "industry" TEXT,
    "website" TEXT,
    "phone" TEXT,
    "notes" TEXT,
    "created_at" BIGINT NOT NULL,
    "created_by" BIGINT,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_companies_by_name" ON "companies" ("name");
CREATE INDEX "index_companies_by_created_by" ON "companies" ("created_by");
CREATE TABLE "contacts" (
    "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" TEXT NOT NULL,
    "last_name" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT,
    "title" TEXT,
    "company_id" BIGINT,
    "notes" TEXT,
    "created_at" BIGINT NOT NULL,
    "created_by" BIGINT,
    PRIMARY KEY ("id")
);
CREATE INDEX "index_contacts_by_email" ON "contacts" ("email");
CREATE INDEX "index_contacts_by_company_id" ON "contacts" ("company_id");
CREATE INDEX "index_contacts_by_created_by" ON "contacts" ("created_by");
