version = 1

[[migrations]]
id = 6812258738138711042
name = "0000_migration.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 6706132347034735827
name = "0001_extra_indexes.sql"
snapshot_name = "0001_snapshot.toml"
