version = 1

[[migrations]]
id = 5158914139429238092
name = "0000_migration.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 1645455760870039706
name = "0001_extra_indexes.sql"
snapshot_name = "0001_snapshot.toml"
