version = 1

[[migrations]]
id = 1253155700344311104
name = "0000_migration.sql"
snapshot_name = "0000_snapshot.toml"

[[migrations]]
id = 2362152825608986056
name = "0001_extra_indexes.sql"
snapshot_name = "0001_snapshot.toml"
