//! Server entry point: read configuration, connect, migrate, seed, serve.

use std::sync::Arc;

use crm_light::auth::Guard;
use crm_light::config::Config;
use crm_light::{App, seed};
use toasty::Db;
use topcoat::cookie::RouterBuilderCookieExt;
use topcoat::router::{Router, RouterBuilderDiscoverExt};

/// Migrations generated by `cargo run --features cli --bin crm-light-cli --
/// migration generate` and compiled into the binary.
///
/// Applying them is idempotent: already-applied migrations are recorded in the
/// database's `__toasty_migrations` table and skipped.
static MIGRATIONS: toasty::migration::MigrationSet = toasty::embed_migrations!();

/// Revoked and expired sessions are kept this long before being swept, so an
/// administrator can still see that a session was revoked.
const SESSION_GRACE_SECONDS: i64 = 7 * 86_400;

#[tokio::main]
async fn main() {
    if let Err(error) = run().await {
        eprintln!("crm-light: {error}");
        std::process::exit(1);
    }
}

async fn run() -> Result<(), Box<dyn std::error::Error>> {
    let (config, warnings) = Config::from_env()?;
    let config = Arc::new(config);

    // The dashboard's aggregates are PostgreSQL SQL and the search asks for
    // `ILIKE`, so a SQLite URL would boot and then fail on the first page that
    // used either. One clear message at startup beats a 500 per request.
    if !config.supports() {
        return Err(format!(
            "CRM_DB is {:?}, which this app cannot run on: its aggregates and search use \
             PostgreSQL SQL. Point CRM_DB at a postgresql:// URL.",
            config.database_url
        )
        .into());
    }

    for warning in &warnings.0 {
        eprintln!("warning: {warning}");
    }

    println!(
        "crm-light: {} at {}, times shown in {}",
        config.driver_name(),
        redact(&config.database_url),
        config.time_zone,
    );
    // Say where to start, without advertising a door that is closed. The host
    // and port are the same variables Topcoat reads, so the line points at
    // where the server is actually listening.
    let host = std::env::var("HOST").unwrap_or_else(|_| "127.0.0.1".to_string());
    let port = std::env::var("PORT").unwrap_or_else(|_| "3000".to_string());
    if config.allow_signup {
        println!("sign up at http://{host}:{port}/signup to create a workspace");
    } else {
        println!(
            "CRM_ALLOW_SIGNUP=0, so /signup is closed; sign in at \
             http://{host}:{port}/login"
        );
    }

    let db = Db::builder()
        .models(toasty::models!(crm_light::*))
        .connect(&config.database_url)
        .await?;

    let report = MIGRATIONS.apply(&db).await?;
    if report.applied() > 0 {
        println!("applied {} migration(s)", report.applied());
    }

    // There is no bootstrap account: a fresh installation is entered through
    // `/signup`, which creates a workspace and makes its first member its
    // administrator. The demo book therefore waits until somebody has signed
    // up, because it needs a workspace to belong to.
    if config.seed_demo_data && seed::seed_demo_data(&db, &config.time_zone).await? {
        println!("seeded the demo book into the first workspace");
    }

    // A long-lived deployment accumulates a session per sign-in; sweeping at
    // startup keeps the table from growing without a separate cron.
    let mut sweep = db.clone();
    let purged = crm_light::auth::purge_sessions(&mut sweep, SESSION_GRACE_SECONDS).await?;
    if purged > 0 {
        println!("purged {purged} expired session(s)");
    }

    // Topcoat binds `HOST`/`PORT` from the environment, defaulting to
    // 127.0.0.1:3000.
    let router = Router::builder()
        .discover()
        // The guard has no path, so it is the outermost layer: it runs before
        // the cookie layer and therefore reads the session cookie straight from
        // the request headers. See `crm_light::auth` for the ordering.
        .layer(Guard::new(db.clone(), Arc::clone(&config)))
        .cookies()
        .app_context(db)
        .app_context(App {
            config: config.as_ref().clone(),
        })
        .app_context(config.time_zone.clone())
        .build();

    topcoat::start(router).await?;
    Ok(())
}

/// Strip credentials out of a connection URL before printing it.
fn redact(url: &str) -> String {
    let Some((scheme, rest)) = url.split_once("://") else {
        return url.to_string();
    };
    match rest.split_once('@') {
        Some((_, host)) => format!("{scheme}://{host}"),
        None => url.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn credentials_are_removed_from_the_banner() {
        assert_eq!(
            redact("postgresql://user:secret@localhost/crm_light"),
            "postgresql://localhost/crm_light"
        );
        assert_eq!(redact("sqlite:crm.db"), "sqlite:crm.db");
        assert_eq!(
            redact("postgresql://localhost/crm_light"),
            "postgresql://localhost/crm_light"
        );
    }

}
