//! Server entry point: connect, migrate, seed, serve.

use crm_light::seed;
use toasty::Db;
use topcoat::router::{Router, RouterBuilderDiscoverExt};

/// Migrations generated by `cargo run --features cli --bin crm-light-cli --
/// migration generate` and compiled into the binary.
///
/// Applying them is idempotent: already-applied migrations are recorded in the
/// database's `__toasty_migrations` table and skipped.
static MIGRATIONS: toasty::migration::MigrationSet = toasty::embed_migrations!();

#[tokio::main]
async fn main() {
    let url = std::env::var("CRM_DB").unwrap_or_else(|_| "sqlite:crm.db".to_string());

    let db = Db::builder()
        .models(toasty::models!(crm_light::*))
        .connect(&url)
        .await
        .expect("connect to SQLite");

    let report = MIGRATIONS.apply(&db).await.expect("apply migrations");
    if report.applied() > 0 {
        println!("applied {} migration(s)", report.applied());
    }

    if std::env::var("CRM_SEED").as_deref() != Ok("0") {
        seed::seed_if_empty(&db).await.expect("seed demo data");
    }

    // Topcoat binds `HOST`/`PORT` from the environment, defaulting to
    // 127.0.0.1:3000.
    topcoat::start(Router::builder().discover().app_context(db).build())
        .await
        .unwrap();
}
