//! Toasty models — each struct maps to one database table.
//!
//! Relationships are plain indexed foreign-key columns (`company_id`,
//! `contact_id`, `deal_id`, `user_id`) rather than `#[belongs_to]`/
//! `#[has_many]` relations, so every query in this app is explicit and easy to
//! follow.
//!
//! Primary keys are `i64`, which both PostgreSQL (`BIGINT`) and SQLite
//! (`INTEGER`) map onto natively; `#[auto]` becomes `GENERATED BY DEFAULT AS
//! IDENTITY` on PostgreSQL and `AUTOINCREMENT` on SQLite.

/// A customer account.
#[derive(Debug, toasty::Model)]
pub struct Company {
    #[key]
    #[auto]
    pub id: i64,

    #[index]
    pub name: String,

    pub industry: Option<String>,
    pub website: Option<String>,
    pub phone: Option<String>,
    pub notes: Option<String>,

    pub created_at: i64,

    /// The user who added the record, when known.
    #[index]
    pub created_by: Option<i64>,
}

/// A person, optionally attached to a company.
#[derive(Debug, toasty::Model)]
pub struct Contact {
    #[key]
    #[auto]
    pub id: i64,

    pub first_name: String,
    pub last_name: String,

    #[index]
    pub email: Option<String>,
    pub phone: Option<String>,
    pub title: Option<String>,

    #[index]
    pub company_id: Option<i64>,

    pub notes: Option<String>,
    pub created_at: i64,

    /// The user who added the record, when known.
    #[index]
    pub created_by: Option<i64>,
}

/// A sales opportunity.
#[derive(Debug, toasty::Model)]
pub struct Deal {
    #[key]
    #[auto]
    pub id: i64,

    pub title: String,

    /// Value in cents; see [`crate::domain::format_money`].
    pub value_cents: i64,

    #[index]
    pub stage: String,

    #[index]
    pub company_id: Option<i64>,

    #[index]
    pub contact_id: Option<i64>,

    /// Expected close date as Unix seconds, normalised to midnight in the
    /// configured display zone.
    pub expected_close: Option<i64>,

    pub notes: Option<String>,
    pub created_at: i64,

    /// The user who added the record, when known.
    #[index]
    pub created_by: Option<i64>,
}

/// A logged interaction, optionally attached to a contact, company, or deal.
#[derive(Debug, toasty::Model)]
pub struct Activity {
    #[key]
    #[auto]
    pub id: i64,

    /// One of `note`, `call`, `email`, `meeting`.
    #[index]
    pub kind: String,

    pub body: String,

    #[index]
    pub contact_id: Option<i64>,

    #[index]
    pub company_id: Option<i64>,

    #[index]
    pub deal_id: Option<i64>,

    pub created_at: i64,

    /// Who logged it. `None` for rows seeded before accounts existed, or left
    /// behind by a deleted user — activities are never deleted with a user.
    #[index]
    pub user_id: Option<i64>,
}

/// An account that can sign in.
#[derive(Debug, toasty::Model)]
pub struct User {
    #[key]
    #[auto]
    pub id: i64,

    /// As typed at sign-up, for display.
    pub username: String,

    /// ASCII-lowercased `username`, which is what login matches on and what the
    /// unique index covers, so `Ada` and `ada` cannot both exist.
    #[unique]
    pub username_lower: String,

    pub display_name: Option<String>,

    /// An Argon2id PHC string, or `None` for an account with no password (the
    /// bootstrap admin, until someone sets one).
    pub password_hash: Option<String>,

    /// One of `admin`, `member`; see [`crate::domain::Role`].
    pub role: String,

    /// Base32 TOTP shared secret, when two-factor is enabled.
    pub totp_secret: Option<String>,

    /// Deactivated accounts keep their rows (and their activity) but cannot log
    /// in, so an audit trail survives someone leaving.
    pub active: bool,

    pub created_at: i64,
    pub last_login_at: Option<i64>,
}

/// A signed-in browser session.
///
/// The cookie carries a random token; only its SHA-256 digest is stored, so a
/// database read does not hand out usable sessions.
#[derive(Debug, toasty::Model)]
pub struct Session {
    #[key]
    #[auto]
    pub id: i64,

    /// Hex SHA-256 of the session token.
    #[unique]
    pub token_hash: String,

    #[index]
    pub user_id: i64,

    pub created_at: i64,

    /// Sessions are absolute, not sliding: the expiry is set at login and only
    /// extended by an explicit re-login.
    pub expires_at: i64,

    /// Set when the session was revoked, so a replay can be distinguished from
    /// an expired session in the logs.
    pub revoked_at: Option<i64>,

    /// Coarse client fingerprint, for the audit view.
    pub user_agent: Option<String>,
    pub ip: Option<String>,
}

/// Failed sign-in bookkeeping, keyed by username.
///
/// This is what makes the "no password" bootstrap account safe to expose: an
/// account with no password still locks after repeated failures.
#[derive(Debug, toasty::Model)]
pub struct LoginAttempt {
    #[key]
    #[auto]
    pub id: i64,

    #[unique]
    pub username_lower: String,

    /// Consecutive failures. Reset to zero on a successful sign-in.
    pub failures: i64,

    /// Unix seconds until which sign-in for this username is refused; `None`
    /// when the account is not locked.
    pub locked_until: Option<i64>,

    pub last_failure_at: i64,
}
