//! Toasty models — each struct maps to one database table.
//!
//! # Tenancy
//!
//! Every row of CRM data carries an `account_id`, and an [`Account`] is the
//! tenant: the set of people who can see each other's records and nobody
//! else's. Signing up creates an account and makes its first member an
//! administrator; that administrator adds the rest.
//!
//! The column is deliberately *not* modelled as a `belongs_to` relation. Every
//! query in this app is written out longhand so the tenant filter is visible at
//! the call site, and a relation that eager-loads would hide exactly the part
//! that must never be forgotten. [`crate::access`] is where the filter and the
//! resulting 403 live.
//!
//! Relationships between the CRM tables are plain indexed foreign-key columns
//! (`company_id`, `contact_id`, `deal_id`) rather than `#[belongs_to]` /
//! `#[has_many]`, for the same reason.
//!
//! Primary keys are `i64`, which both PostgreSQL (`BIGINT`) and SQLite
//! (`INTEGER`) map onto natively; `#[auto]` becomes `GENERATED BY DEFAULT AS
//! IDENTITY` on PostgreSQL and `AUTOINCREMENT` on SQLite.

/// A tenant: one organisation's workspace.
///
/// Everything a member can see belongs to exactly one of these. The slug is
/// what sign-in uses to find the right workspace, since usernames are only
/// unique within one.
#[derive(Debug, toasty::Model)]
pub struct Account {
    #[key]
    #[auto]
    pub id: i64,

    pub name: String,

    /// Lowercased, hyphenated form of the name. Unique, so two workspaces
    /// cannot be told apart by a URL or a sign-in.
    #[unique]
    pub slug: String,

    pub created_at: i64,

    /// The account's first member, for the audit trail. `None` only in the
    /// instant between creating the account and its first user.
    pub created_by: Option<i64>,
}

/// A person who can sign in, belonging to exactly one [`Account`].
#[derive(Debug, toasty::Model)]
pub struct User {
    #[key]
    #[auto]
    pub id: i64,

    /// The tenant this person belongs to.
    #[index]
    pub account_id: i64,

    /// As typed at sign-up, for display.
    pub username: String,

    /// ASCII-lowercased `username`, which is what sign-in matches on.
    ///
    /// Indexed but **not** unique: uniqueness is per account, and Toasty has no
    /// composite unique index for root models. `crate::access` therefore checks
    /// for a clash before it creates a user, and the index makes that check
    /// cheap.
    #[index]
    pub username_lower: String,

    pub display_name: Option<String>,

    /// An Argon2id PHC string, or `None` for an account with no password.
    pub password_hash: Option<String>,

    /// One of `admin`, `member`; see [`crate::domain::Role`].
    pub role: String,

    /// Base32 TOTP shared secret, when two-factor is enabled.
    pub totp_secret: Option<String>,

    /// Deactivated accounts keep their rows (and their activity) but cannot log
    /// in, so an audit trail survives somebody leaving.
    pub active: bool,

    pub created_at: i64,
    pub last_login_at: Option<i64>,
}

/// A signed-in browser session.
///
/// The cookie carries a random token; only its SHA-256 digest is stored, so a
/// database read does not hand out usable sessions.
#[derive(Debug, toasty::Model)]
pub struct Session {
    #[key]
    #[auto]
    pub id: i64,

    /// Hex SHA-256 of the session token.
    #[unique]
    pub token_hash: String,

    /// Carried alongside `user_id` so resolving a request costs one query
    /// rather than two, and so a session can never be read as belonging to a
    /// different tenant than its user.
    #[index]
    pub account_id: i64,

    #[index]
    pub user_id: i64,

    pub created_at: i64,

    /// Sessions are absolute, not sliding: the expiry is set at sign-in and
    /// only extended by an explicit re-sign-in.
    pub expires_at: i64,

    /// Set when the session was revoked, so a replay can be distinguished from
    /// an expired session in the logs.
    pub revoked_at: Option<i64>,

    /// Coarse client fingerprint, for the audit view.
    pub user_agent: Option<String>,
    pub ip: Option<String>,
}

/// Failed sign-in bookkeeping, keyed by account and username.
///
/// Scoped per tenant, so one workspace cannot lock another's people out, and
/// so the throttle cannot be used to probe whether a username exists elsewhere.
#[derive(Debug, toasty::Model)]
pub struct LoginAttempt {
    #[key]
    #[auto]
    pub id: i64,

    #[index]
    pub account_id: i64,

    #[index]
    pub username_lower: String,

    /// Consecutive failures. Reset to zero on a successful sign-in.
    pub failures: i64,

    /// Unix seconds until which sign-in for this username is refused; `None`
    /// when it is not locked.
    pub locked_until: Option<i64>,

    pub last_failure_at: i64,
}

/// A customer account.
#[derive(Debug, toasty::Model)]
pub struct Company {
    #[key]
    #[auto]
    pub id: i64,

    /// The tenant this row belongs to. Every read filters on it.
    #[index]
    pub account_id: i64,

    #[index]
    pub name: String,

    pub industry: Option<String>,
    pub website: Option<String>,
    pub phone: Option<String>,
    pub notes: Option<String>,

    pub created_at: i64,

    /// The user who added the record, when known.
    #[index]
    pub created_by: Option<i64>,
}

/// A person, optionally attached to a company.
#[derive(Debug, toasty::Model)]
pub struct Contact {
    #[key]
    #[auto]
    pub id: i64,

    #[index]
    pub account_id: i64,

    pub first_name: String,
    pub last_name: String,

    #[index]
    pub email: Option<String>,
    pub phone: Option<String>,
    pub title: Option<String>,

    #[index]
    pub company_id: Option<i64>,

    pub notes: Option<String>,
    pub created_at: i64,

    #[index]
    pub created_by: Option<i64>,
}

/// A sales opportunity.
#[derive(Debug, toasty::Model)]
pub struct Deal {
    #[key]
    #[auto]
    pub id: i64,

    #[index]
    pub account_id: i64,

    pub title: String,

    /// Value in cents; see [`crate::domain::format_money`].
    pub value_cents: i64,

    #[index]
    pub stage: String,

    #[index]
    pub company_id: Option<i64>,

    #[index]
    pub contact_id: Option<i64>,

    /// Expected close date as Unix seconds, normalised to midnight in the
    /// configured display zone.
    pub expected_close: Option<i64>,

    pub notes: Option<String>,
    pub created_at: i64,

    #[index]
    pub created_by: Option<i64>,
}

/// A logged interaction, optionally attached to a contact, company, or deal.
#[derive(Debug, toasty::Model)]
pub struct Activity {
    #[key]
    #[auto]
    pub id: i64,

    #[index]
    pub account_id: i64,

    /// One of `note`, `call`, `email`, `meeting`.
    #[index]
    pub kind: String,

    pub body: String,

    #[index]
    pub contact_id: Option<i64>,

    #[index]
    pub company_id: Option<i64>,

    #[index]
    pub deal_id: Option<i64>,

    pub created_at: i64,

    /// Who logged it. `None` for rows left behind by a deleted user —
    /// activities are never deleted with a user.
    #[index]
    pub user_id: Option<i64>,
}
